name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install ARM build toolchain
        run: |
          brew install openocd dfu-util gcc-arm-embedded

      # - name: Build libDaisy dependency
      #   run: |
      #     cd dependencies/kxmx_bluemchen/libDaisy
      #     make

      # - name: Build DaisySP dependency
      #   run: |
      #     cd dependencies/kxmx_bluemchen/DaisySP
      #     make

      # - name: Build app
      #   run: make
